import type {
  RlBallSample,
  RlBoostPickup,
  RlMatchEvent,
  RlParsedReplay,
  RlPlayer,
  RlPositionSample,
} from '@clutchcore/shared';

/** High-fidelity synthetic 3v3 Doubles-style timeline for UI / offline coaching. */
export function buildRlDemoFixture(subjectName = 'You'): RlParsedReplay {
  const durationSeconds = 312;
  const players: RlPlayer[] = [
    {
      id: 'blue-0',
      name: subjectName,
      team: 'blue',
      isSubject: true,
      goals: 1,
      assists: 1,
      saves: 3,
      shots: 5,
      demos: 1,
      score: 482,
      boostUsage: 0.62,
      averageSpeed: 1380,
      ballTouches: 54,
    },
    {
      id: 'blue-1',
      name: 'Teammate',
      team: 'blue',
      isSubject: false,
      goals: 1,
      assists: 0,
      saves: 1,
      shots: 3,
      demos: 0,
      score: 310,
      ballTouches: 41,
    },
    {
      id: 'orange-0',
      name: 'Rival Ace',
      team: 'orange',
      isSubject: false,
      goals: 2,
      assists: 0,
      saves: 2,
      shots: 6,
      demos: 2,
      score: 520,
      ballTouches: 48,
    },
    {
      id: 'orange-1',
      name: 'Rival Support',
      team: 'orange',
      isSubject: false,
      goals: 0,
      assists: 2,
      saves: 2,
      shots: 2,
      demos: 0,
      score: 280,
      ballTouches: 36,
    },
  ];

  const playerTracks: RlPositionSample[] = [];
  const ballTrack: RlBallSample[] = [];
  const boostPickups: RlBoostPickup[] = [];

  for (let t = 0; t <= durationSeconds; t += 0.5) {
    const phase = t / durationSeconds;
    // Subject circles mid with pushes toward orange goal (positive Y)
    playerTracks.push({
      t,
      playerId: 'blue-0',
      x: Math.sin(phase * Math.PI * 6) * 1800,
      y: -2000 + phase * 4500 + Math.sin(phase * 20) * 400,
      z: Math.abs(Math.sin(phase * 12)) * 280,
      boost: Math.max(0, 100 - ((t * 7) % 110)),
      speed: 900 + Math.abs(Math.sin(phase * 14)) * 900,
      onGround: Math.abs(Math.sin(phase * 12)) * 280 < 40,
    });
    playerTracks.push({
      t,
      playerId: 'blue-1',
      x: Math.cos(phase * Math.PI * 5) * 2200,
      y: -2500 + phase * 3000,
      z: 20,
      boost: 40 + ((t * 3) % 60),
      speed: 1100,
      onGround: true,
    });
    playerTracks.push({
      t,
      playerId: 'orange-0',
      x: Math.sin(phase * Math.PI * 4 + 1) * 1600,
      y: 2500 - phase * 3500,
      z: 30,
      boost: 55,
      speed: 1200,
      onGround: true,
    });
    playerTracks.push({
      t,
      playerId: 'orange-1',
      x: -Math.cos(phase * Math.PI * 3) * 1400,
      y: 2800 - phase * 2800,
      z: 25,
      boost: 70,
      speed: 1000,
      onGround: true,
    });

    ballTrack.push({
      t,
      x: Math.sin(phase * Math.PI * 8) * 1200,
      y: -1500 + phase * 4000 + Math.sin(phase * 30) * 600,
      z: 100 + Math.abs(Math.sin(phase * 18)) * 600,
      speed: 1200 + Math.abs(Math.cos(phase * 22)) * 1400,
    });

    if (t % 8 === 0) {
      boostPickups.push({
        t,
        playerId: t % 16 === 0 ? 'blue-0' : 'blue-1',
        padId: `pad-${(t / 8) % 6}`,
        amount: t % 16 === 0 ? 100 : 12,
        isBigPad: t % 16 === 0,
        x: Math.sin(phase * 10) * 3000,
        y: Math.cos(phase * 10) * 4000,
      });
    }
  }

  const events: RlMatchEvent[] = [
    {
      id: 'ev-kickoff-1',
      t: 0,
      type: 'kickoff',
      label: 'Kickoff — left bias cheat',
      actorId: 'blue-0',
      position: { x: 0, y: -4600, z: 20 },
      ballPosition: { x: 0, y: 0, z: 93 },
      boost: 33,
      speed: 0,
    },
    {
      id: 'ev-whiff-1',
      t: 38,
      type: 'whiff',
      label: 'Whiffed ground touch midfield',
      actorId: 'blue-0',
      position: { x: 200, y: -200, z: 20 },
      ballPosition: { x: 260, y: -140, z: 120 },
      boost: 18,
      speed: 1400,
    },
    {
      id: 'ev-double-1',
      t: 72,
      type: 'double_commit',
      label: 'Double commit with teammate',
      actorId: 'blue-0',
      position: { x: -400, y: 800, z: 20 },
      ballPosition: { x: -350, y: 900, z: 200 },
      boost: 45,
      speed: 1600,
    },
    {
      id: 'ev-goal-opp-1',
      t: 76,
      type: 'goal',
      label: 'Conceded — open net after double commit',
      actorId: 'orange-0',
      team: 'orange',
      position: { x: 0, y: -5120, z: 200 },
      ballPosition: { x: 40, y: -5200, z: 250 },
    },
    {
      id: 'ev-save-1',
      t: 118,
      type: 'save',
      label: 'Backboard save',
      actorId: 'blue-0',
      position: { x: 200, y: -4800, z: 600 },
      ballPosition: { x: 180, y: -5000, z: 700 },
      boost: 12,
      speed: 1100,
    },
    {
      id: 'ev-boost-starve-1',
      t: 145,
      type: 'missed_boost',
      label: 'Rotated through empty corner — starved',
      actorId: 'blue-0',
      position: { x: 3072, y: -4096, z: 20 },
      boost: 0,
      speed: 900,
    },
    {
      id: 'ev-shot-1',
      t: 168,
      type: 'shot',
      label: 'Low 50 redirect shot',
      actorId: 'blue-0',
      position: { x: -300, y: 3200, z: 40 },
      ballPosition: { x: -280, y: 3600, z: 180 },
      boost: 55,
      speed: 1500,
    },
    {
      id: 'ev-miss-open-1',
      t: 201,
      type: 'missed_open_net',
      label: 'Missed open net from mid',
      actorId: 'blue-0',
      position: { x: 100, y: 2100, z: 20 },
      ballPosition: { x: 80, y: 2800, z: 140 },
      boost: 70,
      speed: 1300,
    },
    {
      id: 'ev-overcommit-1',
      t: 224,
      type: 'overcommit',
      label: 'Overcommitted challenge on backline',
      actorId: 'blue-0',
      position: { x: -100, y: -1800, z: 20 },
      ballPosition: { x: -80, y: -1600, z: 100 },
      boost: 22,
      speed: 1700,
    },
    {
      id: 'ev-goal-opp-2',
      t: 231,
      type: 'goal',
      label: 'Conceded — slow recover to back post',
      actorId: 'orange-1',
      team: 'orange',
      position: { x: 400, y: -5120, z: 150 },
      ballPosition: { x: 420, y: -5250, z: 200 },
    },
    {
      id: 'ev-demo-1',
      t: 255,
      type: 'demo',
      label: 'Demo on last man before cross',
      actorId: 'blue-0',
      targetId: 'orange-1',
      position: { x: -800, y: 4200, z: 20 },
      boost: 40,
      speed: 2000,
    },
    {
      id: 'ev-assist-1',
      t: 258,
      type: 'assist',
      label: 'Centering pass after demo',
      actorId: 'blue-0',
      position: { x: -600, y: 3800, z: 40 },
      ballPosition: { x: 0, y: 4500, z: 300 },
      boost: 15,
    },
    {
      id: 'ev-goal-1',
      t: 260,
      type: 'goal',
      label: 'Teammate tap-in',
      actorId: 'blue-1',
      team: 'blue',
      position: { x: 100, y: 5120, z: 120 },
      ballPosition: { x: 80, y: 5200, z: 140 },
    },
    {
      id: 'ev-aerial-1',
      t: 278,
      type: 'aerial',
      label: 'Contested aerial 50/50',
      actorId: 'blue-0',
      position: { x: 0, y: 0, z: 900 },
      ballPosition: { x: 20, y: 40, z: 950 },
      boost: 60,
      speed: 1600,
    },
    {
      id: 'ev-excellent-1',
      t: 295,
      type: 'excellent_play',
      label: 'Shadow to challenge — forced weak touch',
      actorId: 'blue-0',
      position: { x: 300, y: -2200, z: 20 },
      ballPosition: { x: 250, y: -1800, z: 200 },
      boost: 35,
      speed: 1200,
    },
    {
      id: 'ev-goal-2',
      t: 305,
      type: 'goal',
      label: 'Power shot far post',
      actorId: 'blue-0',
      team: 'blue',
      position: { x: -400, y: 3600, z: 30 },
      ballPosition: { x: 600, y: 5200, z: 280 },
      boost: 48,
      speed: 1550,
    },
  ];

  return {
    metadata: {
      map: 'DFH Stadium',
      date: new Date().toISOString(),
      durationSeconds,
      playlist: 'ranked_doubles',
      rank: 'Champion I',
      mmr: 1120,
      scoreBlue: 2,
      scoreOrange: 2,
      overtime: false,
      players,
      version: 'fixture-1.0',
      game: 'rocket-league',
    },
    subjectPlayerId: 'blue-0',
    playerTracks,
    ballTrack,
    boostPickups,
    events,
    extractionConfidence: 'partial',
    parserNotes: [
      'Demo fixture timeline (no Ballchasing API key). Re-upload with BALLCHASING_API_KEY for full extraction.',
    ],
    source: 'fixture',
  };
}
